# golangci-lint v2.x configuration
version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - revive

revive:
  rules:
    - name: package-comments
    - name: exported
    - name: redefines-builtin-id
    - name: empty-block
    - name: unused-parameter
    - name: var-declaration
    - name: indent-error-flow
