# golangci-lint v2.x minimal configuration
version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  default: standard
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
