# golangci-lint v2.x configuration
version: "2"

run:
  timeout: 5m
  go: "1.25"
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
  settings:
    govet:
      shadow:
        strict: false
    errcheck:
      check-type-assertions: false
      check-blank: false
    staticcheck:
      checks: ["all"]

issues:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
      - path: cmd/redactctl/main\.go
        linters:
          - unused
