# golangci-lint v2.4.0 minimal working configuration
version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
