#!/usr/bin/env bash
# Print the CHANGELOG section for a version so GitHub Releases ship the
# same notes as CHANGELOG.md (not only autogenerated commit lists).
#
# Usage:
#   changelog-notes.sh <version-without-v> [CHANGELOG.md]
#   changelog-notes.sh --self-test
set -euo pipefail

usage() {
  echo "Usage: changelog-notes.sh <version> [CHANGELOG.md]" >&2
  echo "       changelog-notes.sh --self-test" >&2
}

extract() {
  local ver="$1"
  local file="$2"
  ver="${ver#v}"
  python3 - "$file" "$ver" <<'PY'
import sys

path, ver = sys.argv[1], sys.argv[2]
lines = open(path, encoding="utf-8").read().splitlines()
start = next((i for i, line in enumerate(lines) if line.startswith(f"## [{ver}]")), None)
if start is None:
    sys.exit(f"CHANGELOG.md has no ## [{ver}] section")
end = len(lines)
for i in range(start + 1, len(lines)):
    if lines[i].startswith("## ["):
        end = i
        break
body = lines[start:end]
while body and not body[-1].strip():
    body.pop()
sys.stdout.write("\n".join(body) + "\n")
PY
}

self_test() {
  local tmp
  tmp="$(mktemp)"
  cat >"$tmp" <<'EOF'
# Changelog

## [0.10.0] - 2026-08-16

### Added

- example

## [0.9.1] - 2026-08-08

### Fixed

- older
EOF
  local got
  got="$(extract 0.10.0 "$tmp")"
  echo "$got" | grep -q '## \[0.10.0\]' || { echo "missing 0.10.0 heading" >&2; exit 1; }
  echo "$got" | grep -q 'example' || { echo "missing 0.10.0 body" >&2; exit 1; }
  echo "$got" | grep -q '0.9.1' && { echo "0.10.0 extract leaked 0.9.1" >&2; exit 1; }
  got="$(extract v0.9.1 "$tmp")"
  echo "$got" | grep -q '## \[0.9.1\]' || { echo "missing 0.9.1 heading" >&2; exit 1; }
  rm -f "$tmp"
  echo "OK: changelog-notes.sh self-test"
}

if [[ "${1:-}" == "--self-test" ]]; then
  self_test
  exit 0
fi

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

extract "$1" "${2:-CHANGELOG.md}"
